# Generated by Django 5.1.4 on 2024-12-28 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('viewflow_base', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTProcess',
            fields=[
                ('process_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='viewflow_base.process')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('text', models.CharField(help_text='Please state the reason for OT.', max_length=150)),
                ('approved', models.BooleanField(default=False)),
                ('hours', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('viewflow_base.process',),
        ),
    ]
