# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcc', models.CharField(max_length=5)),
                ('mnc', models.CharField(max_length=5)),
                ('brand', models.CharField(blank=True, max_length=50, null=True)),
                ('operator', models.CharField(blank=True, max_length=50, null=True)),
                ('bands', models.CharField(blank=True, max_length=2000, null=True)),
                ('mvno', models.BooleanField()),
                ('mno', models.CharField(blank=True, max_length=20, null=True)),
                ('remark', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
    ]
