# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 13:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.CharField(auto_created=True, blank=True, max_length=20, primary_key=True, serialize=False)),
                ('brand', models.CharField(blank=True, max_length=20, null=True)),
                ('model', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('date_in', models.DateField(blank=True, null=True)),
                ('date_out', models.DateField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.Category')),
                ('now_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DUT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=20)),
                ('hw_status', models.CharField(max_length=20, null=True)),
                ('use', models.CharField(blank=True, max_length=100, null=True)),
                ('date_get', models.DateField(null=True)),
                ('date_return', models.DateField(blank=True, null=True)),
                ('shipment', models.CharField(max_length=20, null=True)),
                ('remarks', models.CharField(blank=True, max_length=2000, null=True)),
                ('battery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='device.Battery')),
                ('now_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DUTReturned',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=20)),
                ('hw_status', models.CharField(max_length=20, null=True)),
                ('use', models.CharField(blank=True, max_length=100, null=True)),
                ('date_get', models.DateField(null=True)),
                ('date_return', models.DateField(blank=True, null=True)),
                ('shipment', models.CharField(max_length=20, null=True)),
                ('remarks', models.CharField(blank=True, max_length=2000, null=True)),
                ('battery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='device.Battery')),
                ('now_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('status_code', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='dutreturned',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='device.Status'),
        ),
        migrations.AddField(
            model_name='dut',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='device.Status'),
        ),
        migrations.AddField(
            model_name='device',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='device.Status'),
        ),
    ]
