# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('model_name', models.CharField(blank=True, max_length=20, null=True)),
                ('mkt_name', models.CharField(blank=True, max_length=20, null=True)),
                ('color_os_ver', models.CharField(blank=True, max_length=10, null=True)),
                ('android_ver', models.CharField(blank=True, max_length=10, null=True)),
                ('processor', models.CharField(blank=True, max_length=50, null=True)),
                ('ram', models.CharField(blank=True, max_length=10, null=True)),
                ('internal_storage', models.CharField(blank=True, max_length=10, null=True)),
                ('resolution', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
